version: '3.8'

services:
  spark-master:
    image: apache/spark:3.5.0-python3
    container_name: spark-master
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "8082:8080"
      - "7077:7077"
      - "6066:6066"
    environment:
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
    volumes:
      - ./jobs:/opt/spark/jobs
      - ./data:/opt/spark/data
    networks:
      - pyspark-network

  spark-worker:
    image: apache/spark:3.5.0-python3
    container_name: spark-worker
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    ports:
      - "8081:8081"
    depends_on:
      - spark-master
    environment:
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
    volumes:
      - ./jobs:/opt/spark/jobs
      - ./data:/opt/spark/data
    networks:
      - pyspark-network

  jupyter:
    image: jupyter/pyspark-notebook:latest
    container_name: pyspark-jupyter
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./jobs:/home/jovyan/jobs
      - ./data:/home/jovyan/data
    networks:
      - pyspark-network
    command: start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''
    depends_on:
      - spark-master

  postgres:
    image: postgres:16-alpine
    container_name: pyspark-postgres
    environment:
      POSTGRES_USER: pyspark_user
      POSTGRES_PASSWORD: pyspark_pass
      POSTGRES_DB: pyspark_db
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - pyspark-network

networks:
  pyspark-network:
    driver: bridge

volumes:
  postgres-data:
